{{- if .Values.ingress.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  entryPoints:
    - {{ .Values.ingress.entryPoint | default "web" }}
  routes:
    - match: {{ .Values.ingress.matchRule | default "Host(`{{ .Values.ingress.host }}`)" }}
      kind: Rule
      {{- if and (eq .Values.rollout.strategy.type "canary") .Values.rollout.strategy.canary.traefik }}
      services:
        - name: {{ .Chart.Name }}-root
          kind: TraefikService
      {{- else }}
      services:
        - name: {{ .Chart.Name }}-active
          port: {{ .Values.service.externalPort }}
      {{- end }}
      {{- if .Values.ingress.middlewares }}
      middlewares:
{{ toYaml .Values.ingress.middlewares | indent 8 }}
      {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end }}
{{- end }}
