apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: deals-ingress-route
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: deals-traefik-service
          kind: TraefikService
          port: service