apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: deals-traefik-service
  namespace: default
  labels:
    app: deals
spec:
  weighted:
    services:
      - name: deals-active
        port: 80
      - name: deals-preview
        port: 80
