namespace: default

image:
  repository: ghcr.io/devops-estudos/deals
  tag: latest
  pullPolicy: Always

replicaCount: 1

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 3000
  annotations: {}

# Traefik IngressRoute configuration
ingress:
  enabled: true
  host: deals.local
  entryPoint: web
  matchRule: PathPrefix(`/deals`)
  middlewares: []
  tls: {}

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Argo Rollouts configuration
rollout:
  revisionHistoryLimit: 10
  strategy:
    type: blueGreen  # Options: blueGreen, canary
    blueGreen:
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 30
      scaleDownDelayRevisionLimit: 2
    # canary:
    #   steps:
    #     - setWeight: 20
    #     - pause: {duration: 10}
    #     - setWeight: 40
    #     - pause: {duration: 10}
    #     - setWeight: 60
    #     - pause: {duration: 10}
    #     - setWeight: 80
    #     - pause: {duration: 10}
    #   traefik: true
    #   trafficRouting:
    #     traefik:
    #       weightedTraefikServiceName: deals-weighted
    #       rootServiceName: deals-root