name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
            version: 10
      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deals
          path: dist
  
  publish:
    runs-on: ubuntu-22.04
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v4
        with:
          name: deals
          path: dist
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/devops-estudos/deals
          tags: |
            type=raw,value=latest
            type=sha,prefix=,format=long
            type=sha,prefix=,format=short
          labels: |
            com.github.actions.source-url=https://github.com/devops-estudos/deals
            com.github.actions.source-ref=HEAD
            com.github.actions.source-sha=${{ github.sha }}
            com.github.actions.source-ref-name=${{ github.ref_name }}
            com.github.actions.source-ref-type=${{ github.ref_type }}
            com.github.actions.source-ref-sha=${{ github.ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true

          context: .

          cache-from: type=gha
          cache-to: type=gha,mode=max

          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}




      


      
  